name: build-docs

on:
    workflow_dispatch:
    pull_request:
        paths:
            - docs/**

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: docs
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v6
              with:
                  node-version: 22
                  cache: pnpm
            - run: pnpm install
            - run: pnpm docs:build
